# Use wildcard * to display all endpoints
# Can also expose individual endpoints using comma-delimited list
spring.application.name = mySpringApp
# management.endpoints.web.exposure.include = health,info
# Expose all endpoints
management.endpoints.web.exposure.include = *

# Exclude some endpoints
# management.endpoints.web.exposure.exclude = health,info

management.info.env.enabled=true

# Any property starting with info.xx will come under actuator/info
# Can be used as meta data and configuration
info.app.name = My first Springboot app
info.app.description = The description of the app
info.app.version = 1.0.0